SELECT b.AUTHOR_ID,
       AUTHOR_NAME,
       CATEGORY,
       SUM(bs.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK AS b JOIN 
     AUTHOR AS a JOIN
     BOOK_SALES AS bs ON b.AUTHOR_ID = a.AUTHOR_ID AND b.BOOK_ID = bs.BOOK_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY 1,
         3 DESC