SELECT fp.PRODUCT_ID,
       fp.PRODUCT_NAME,
       SUM(fp.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS fp join FOOD_ORDER AS fo on fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE SUBSTR(fo.PRODUCE_DATE, 1, 7) = "2022-05"
GROUP BY PRODUCT_NAME
ORDER BY 3 DESC,
         1