SELECT MEMBER_NAME,
       REVIEW_TEXT,
       DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS mp JOIN REST_REVIEW AS rr ON mp.MEMBER_ID = rr.MEMBER_ID
WHERE rr.MEMBER_ID = (
    SELECT MEMBER_ID 
    FROM REST_REVIEW R 
    GROUP BY 1
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY 3, 2